refactor($quartz): create another instance instead of casting object
java.lang.ClassCastException: class com.jmsoftware.maf.springcloudstarter.quartz.entity.persistence.QuartzJobConfiguration cannot be cast to class com.jmsoftware.maf.springcloudstarter.quartz.entity.persistence.QuartzJobConfiguration (com.jmsoftware.maf.springcloudstarter.quartz.entity.persistence.QuartzJobConfiguration is in unnamed module of loader 'app'; com.jmsoftware.maf.springcloudstarter.quartz.entity.persistence.QuartzJobConfiguration is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @28e47ab1)
	at com.jmsoftware.maf.springcloudstarter.quartz.job.AbstractQuartzJob.executeInternal(AbstractQuartzJob.java:30)